Repository stripe/stripe-android, pull requests merged in 2023-09, with the labels that each got.

#7265 [Identity] bump up example app version
  identity-example/build.gradle
Labels: accept-risky-change

#7331 [Android] Navigating back from institution picker requires two taps
  CHANGELOG.md
  financial-connections/src/main/java/com/stripe/android/financialconnections/navigation/NavigationManager.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/ui/FinancialConnectionsSheetNativeActivity.kt
Labels: work-cli

#7333 [FC] Example app: Removes view binding.
  financial-connections-example/build.gradle
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsBankAccountTokenExampleActivity.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsDataExampleActivity.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsLauncherActivity.kt
Labels: accept-risky-change

#7344 Live events skeleton implementation
  financial-connections-example/build.gradle
  financial-connections-example/src/main/AndroidManifest.xml
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsDataExampleActivity.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsDataExampleActivityJava.java
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsExampleViewModel.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsLauncherActivity.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsPlaygroundActivity.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsPlaygroundViewModel.kt
  financial-connections-example/src/main/res/values/strings.xml
  financial-connections/api/financial-connections.api
  financial-connections/src/main/java/com/stripe/android/financialconnections/FinancialConnections.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/FinancialConnectionsSheet.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/FinancialConnectionsSheetViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/analytics/DefaultFinancialConnectionsEventReporter.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/analytics/FinancialConnectionsAnalyticsEvent.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/analytics/FinancialConnectionsAnalyticsTracker.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/analytics/FinancialConnectionsEvent.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/analytics/FinancialConnectionsEventListener.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/accountpicker/AccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/attachpayment/AttachPaymentViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/consent/ConsentViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/institutionpicker/InstitutionPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkstepupverification/LinkStepUpVerificationViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/manualentry/ManualEntryViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/manualentrysuccess/ManualEntrySuccessViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/networkinglinkloginwarmup/NetworkingLinkLoginWarmupViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/networkinglinksignup/NetworkingLinkSignupViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/networkinglinkverification/NetworkingLinkVerificationViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/networkingsavetolinkverification/NetworkingSaveToLinkVerificationViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/partnerauth/PartnerAuthViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/reset/ResetViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/success/SuccessViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/presentation/FinancialConnectionsSheetNativeViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/utils/Experiments.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/FinancialConnectionsSheetViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/TestFinancialConnectionsAnalyticsTracker.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/domain/NativeAuthFlowRouterTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/success/SuccessViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/utils/ExperimentsTest.kt
Labels: work-cli, accept-risky-change
