Repository stripe/stripe-android, pull requests merged in 2024-07, with the labels that each got.

#8602 Pass `hosted_surface` correctly across surfaces.
  payments-core/src/main/java/com/stripe/android/model/CreateFinancialConnectionsSessionForDeferredPaymentParams.kt
  payments-core/src/main/java/com/stripe/android/model/CreateFinancialConnectionsSessionParams.kt
  payments-core/src/main/java/com/stripe/android/payments/bankaccount/CollectBankAccountForACHLauncher.kt
  payments-core/src/main/java/com/stripe/android/payments/bankaccount/CollectBankAccountForInstantDebitsLauncher.kt
  payments-core/src/main/java/com/stripe/android/payments/bankaccount/CollectBankAccountLauncher.kt
  payments-core/src/main/java/com/stripe/android/payments/bankaccount/domain/CreateFinancialConnectionsSession.kt
  payments-core/src/main/java/com/stripe/android/payments/bankaccount/navigation/CollectBankAccountContract.kt
  payments-core/src/main/java/com/stripe/android/payments/bankaccount/ui/CollectBankAccountViewModel.kt
  payments-core/src/test/java/com/stripe/android/networking/StripeApiRepositoryTest.kt
  payments-core/src/test/java/com/stripe/android/payments/bankaccount/CollectBankAccountForACHLauncherTest.kt
  payments-core/src/test/java/com/stripe/android/payments/bankaccount/domain/CreateFinancialConnectionsSessionTest.kt
  payments-core/src/test/java/com/stripe/android/payments/bankaccount/ui/CollectBankAccountViewModelTest.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountForm.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountFormArguments.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountFormViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/AddPaymentMethodInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeFormInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetScreenshotTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/utils/CustomerSheetTestHelper.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountFormViewModelTest.kt
Labels: work-cli

#8730 [Android] Unsupportability: Initial institution is erased when navigating from LinkAccountPicker to PartnerAuth
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/partnerauth/PartnerAuthViewModel.kt
Labels: work-cli

#8729 Update account item UI to support NME
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/common/AccountItem.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/model/FinancialConnectionsGenericInfoScreen.kt
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.accountpicker_null_AccountPickerPane_AccountPickerPreview_0_null_2,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.accountpicker_null_AccountPickerPane_AccountPickerPreview_0_null_2,PIXEL_C].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.accountpicker_null_AccountPickerPane_AccountPickerPreview_0_null_3,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.accountpicker_null_AccountPickerPane_AccountPickerPreview_0_null_3,PIXEL_C].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.common_null_DefaultGroup_AccountItemPreview_0_null,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.common_null_DefaultGroup_AccountItemPreview_0_null,PIXEL_C].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_0,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_0,PIXEL_C].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_2,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_2,PIXEL_C].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_3,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_3,PIXEL_C].png
Labels: work-cli

#8770 Wait for link button to not be enabled before asserting
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetActivityTest.kt
Labels: flake-fix

#8803 Fix a flakey test.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SelectSavedPaymentMethodsInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/DefaultSelectSavedPaymentMethodsInteractorTest.kt
Labels: flake-fix

#8815 Make mandates resolvable strings.
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewAction.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewState.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/ui/CustomerSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/model/MandateText.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/model/PaymentSelection.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountEmitters.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountFormArguments.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountFormScreenState.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountFormViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountTextBuilder.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/UsBankAccountFormArgumentsKtx.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/viewmodels/BaseSheetViewModel.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetScreenshotTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentOptionsActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/model/PaymentSelectionTest.kt
  stripe-core/api/stripe-core.api
  stripe-core/src/main/java/com/stripe/android/core/strings/IdentifierResolvableString.kt
  stripe-core/src/main/java/com/stripe/android/core/strings/ResolvableStringUtils.kt
  stripe-core/src/main/java/com/stripe/android/core/strings/transformations/Replace.kt
  stripe-core/src/main/java/com/stripe/android/core/strings/transformations/TransformOperation.kt
  stripe-core/src/test/java/com/stripe/android/core/strings/ResolvableStringTest.kt
  stripe-core/src/test/java/com/stripe/android/core/strings/transformations/ReplaceTest.kt
Labels: BaseSheetViewModelRefactors

#8814 Add step for creating a version bump PR
  scripts/deploy/common.rb
  scripts/deploy/deploy.rb
  scripts/deploy/github_steps.rb
Labels: release-process-improvement

#8828 Move top bar state to be screen specific.
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewState.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/ui/CustomerSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutator.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/bacs/BacsMandateConfirmationActivity.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/AddPaymentMethodInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/EditPaymentMethodViewInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBar.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBarState.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SelectSavedPaymentMethodsInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageOneSavedPaymentMethodInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeFormInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/viewmodels/BaseSheetViewModel.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetScreenshotTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/utils/CustomerSheetTestHelper.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/FakeEditPaymentMethodInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/FakeSelectSavedPaymentMethodsInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutatorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/navigation/FakeAddPaymentMethodInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreenEditPaymentMethodTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreenManageSavedPaymentMethodsTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/AddPaymentMethodTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/DefaultAddPaymentMethodInteractorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/DefaultEditPaymentMethodViewInteractorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/DefaultSelectSavedPaymentMethodsInteractorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/FakeAddPaymentMethodInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBarScreenshotTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBarStateFactoryTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBarTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/utils/FakeEditPaymentMethodInteractorFactory.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultManageScreenInteractorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultPaymentMethodVerticalLayoutInteractorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/FakeManageScreenInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/ManageOneSavedPaymentMethodUITest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenUIScreenshotTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenUITest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutUITest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeFormUITest.kt
Labels: BaseSheetViewModelRefactors

#8829 Move google pay into PaymentMethodMetadata.
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetLoader.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetState.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/lpmfoundations/paymentmethod/PaymentMethodMetadata.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutator.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/flowcontroller/PaymentSelectionUpdater.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/state/GooglePayState.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/state/PaymentSheetLoader.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/state/PaymentSheetState.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/state/WalletsState.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/viewmodels/BaseSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/viewmodels/PaymentOptionsItemsMapper.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/state/DefaultCustomerSheetLoaderTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/utils/CustomerSheetTestHelper.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/utils/FakeCustomerSheetLoader.kt
  paymentsheet/src/test/java/com/stripe/android/lpmfoundations/paymentmethod/PaymentMethodMetadataFactory.kt
  paymentsheet/src/test/java/com/stripe/android/lpmfoundations/paymentmethod/PaymentMethodMetadataTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentOptionsViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetFixtures.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutatorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/flowcontroller/DefaultFlowControllerTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/flowcontroller/PaymentSelectionUpdaterTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/state/DefaultPaymentSheetLoaderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/viewmodels/PaymentOptionsItemsMapperTest.kt
  paymentsheet/src/test/java/com/stripe/android/utils/FakePaymentSheetLoader.kt
  paymentsheet/src/test/java/com/stripe/android/utils/RelayingPaymentSheetLoader.kt
Labels: BaseSheetViewModelRefactors

#8850 Pass SavedPaymentMethodMutator to interactors.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SelectSavedPaymentMethodsInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageOneSavedPaymentMethodInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeInitialScreenFactory.kt
Labels: BaseSheetViewModelRefactors

#8852 Move SavedPaymentMethodTabLayoutUI out of centralized screen.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SavedPaymentMethodTabLayoutUI.kt
Labels: BaseSheetViewModelRefactors

#8853 Fix vertical mode form back button.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeFormInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreenFormTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreenVerticalModeFormTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultVerticalModeFormInteractorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeFormUITest.kt
Labels: vertical-mode

#8851 Move click disablement while in editing to the UI.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SavedPaymentMethodTabLayoutUI.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentOptionsViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/PaymentOptionsTest.kt
Labels: BaseSheetViewModelRefactors

#8870 Add step to update changelog to our new deploy script
  scripts/deploy/deploy.rb
  scripts/deploy/github_steps.rb
  scripts/deploy/update_version_numbers.rb
Labels: release-process-improvement

#8856 Update click UX for "disabled" items.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/RowButton.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SavedPaymentMethodTab.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SavedPaymentMethodTabLayoutUI.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenUI.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodRowButton.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/SavedPaymentMethodRowButton.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenUITest.kt
Labels: vertical-mode

#8890 Get isEditing from the current screen.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/bacs/BacsMandateConfirmationActivity.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBar.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBarState.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/viewmodels/BaseSheetViewModel.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBarScreenshotTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBarStateFactoryTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/PaymentSheetTopBarTest.kt
Labels: BaseSheetViewModelRefactors

#8894 Click button to edit.
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetActivityTest.kt
Labels: BaseSheetViewModelRefactors

#8901 Remove implementation detail knowledge from PaymentSheetActivityTest.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SavedPaymentMethodTab.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/utils/FakePaymentSheetLoader.kt
Labels: BaseSheetViewModelRefactors

#8911 Move SavedPaymentMethodMutator specific logic to it's test class.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutator.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentOptionsViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutatorTest.kt
Labels: BaseSheetViewModelRefactors

#8912 Move CustomerStateHolder specific logic to it's test class.
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/CustomerStateHolderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentOptionsViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetViewModelTest.kt
Labels: BaseSheetViewModelRefactors

#8915 PaymentMethodMetadata isn't a flow for PaymentOptionsViewModel.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsViewModel.kt
Labels: BaseSheetViewModelRefactors

#8917 Use `paymentMethodMetadata` directly in walletsState.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
Labels: BaseSheetViewModelRefactors

#8927 Add step to update pay server docs to new deploy script
  scripts/deploy/common.rb
  scripts/deploy/deploy.rb
  scripts/deploy/update_dokka.rb
  scripts/deploy/update_pay_server_docs.rb
  scripts/deploy/update_version_numbers.rb
  scripts/deploy/version_bump_pr_steps.rb
Labels: release-process-improvement

#8766 Display data access notice from server on LinkAccountPicker
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerPreviewParameterProvider.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerScreen.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/model/TextUpdate.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModelTest.kt
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_0,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_0,PIXEL_C].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_2,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_2,PIXEL_C].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_3,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.linkaccountpicker_null_LinkAccountPickerPane_LinkAccountPickerScreenPreview_0_null_3,PIXEL_C].png
Labels: work-cli

#8931 Handle navigating to RUX when clicking manual entry CTA on consent
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/consent/ConsentState.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/consent/ConsentViewModel.kt
Labels: work-cli

#8934 Add publish to sonatype step to new release script
  Gemfile
  Gemfile.lock
  scripts/deploy/deploy.rb
  scripts/deploy/publish_to_sonatype.rb
Labels: release-process-improvement

#8938 Update dry run verification steps for new release script
  scripts/deploy/create_github_release.rb
  scripts/deploy/deploy.rb
  scripts/deploy/update_dokka.rb
  scripts/deploy/version_bump_pr_steps.rb
Labels: release-process-improvement

#8943 Consolidate version bump steps in release script
  scripts/deploy/create_github_release.rb
  scripts/deploy/deploy.rb
  scripts/deploy/version_bump_pr_steps.rb
Labels: release-process-improvement

#8743 Handle `drawer_on_selection` UI
  financial-connections/api/financial-connections.api
  financial-connections/detekt-baseline.xml
  financial-connections/src/main/java/com/stripe/android/financialconnections/di/FinancialConnectionsSheetNativeModule.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/accountpicker/AccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/common/AccountItem.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/common/ModalBottomSheetContent.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/common/ShapedIcon.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/common/SharedPartnerAuth.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/consent/ConsentViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/generic/GenericScreen.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/generic/GenericScreenPreviewParameterProvider.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/networkinglinksignup/NetworkingLinkSignupViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/notice/NoticeSheet.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/notice/NoticeSheetViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/notice/PresentSheet.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/partnerauth/PartnerAuthViewModel.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/accountpicker/AccountPickerViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/networkinglinksignup/NetworkingLinkSignupViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/partnerauth/PartnerAuthViewModelTest.kt
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.generic_null_DefaultGroup_GenericScreenPreview_0_null_0,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.generic_null_DefaultGroup_GenericScreenPreview_0_null_0,PIXEL_C].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.generic_null_DefaultGroup_GenericScreenPreview_0_null_1,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.generic_null_DefaultGroup_GenericScreenPreview_0_null_1,PIXEL_C].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.generic_null_DefaultGroup_GenericScreenPreview_0_null_2,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.generic_null_DefaultGroup_GenericScreenPreview_0_null_2,PIXEL_C].png
Labels: work-cli

#8960 Add step to update VERSION file in release process
  scripts/deploy/update_version_numbers.rb
  scripts/deploy/version_bump_pr_steps.rb
Labels: release-process-improvement

#8946 Move AccountUpdateRequired drawer to SDUI (GenericContent)
  financial-connections/api/financial-connections.api
  financial-connections/res/values/strings.xml
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/accountupdate/AccountUpdateRequiredModal.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/accountupdate/AccountUpdateRequiredViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/common/ModalBottomSheetContent.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/common/ShapedIcon.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/generic/GenericScreen.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/notice/NoticeSheet.kt
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.accountupdate_null_AccountUpdateRequiredModal_AccountUpdateRequiredModalPreview_0_null,NEXUS_5].png
  financial-connections/src/test/snapshots/images/com.stripe.android.financialconnections.screenshottests_PaparazziSampleScreenshotTest_preview_tests[com.stripe.android.financialconnections.features.accountupdate_null_AccountUpdateRequiredModal_AccountUpdateRequiredModalPreview_0_null,PIXEL_C].png
Labels: work-cli

#8963 Update release script to ensure that the github and sonatype releases are done from the release branch
  scripts/deploy/common.rb
  scripts/deploy/create_github_release.rb
  scripts/deploy/publish_to_sonatype.rb
  scripts/deploy/version_bump_pr_steps.rb
Labels: release-process-improvement

#8961 Use server provided nextPane value to tell the server where Link Login opt out should go
  financial-connections/src/main/java/com/stripe/android/financialconnections/domain/DisableNetworking.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/domain/SaveAccountToLink.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/consent/ConsentViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/networkinglinkloginwarmup/NetworkingLinkLoginWarmupScreen.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/networkinglinkloginwarmup/NetworkingLinkLoginWarmupViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/navigation/Destination.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/repository/FinancialConnectionsManifestRepository.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/ui/HandleClickableUrl.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/domain/SaveAccountToLinkTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/networkinglinkloginwarmup/NetworkingLinkLoginWarmupViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/navigation/DestinationTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/networking/AbsFinancialConnectionsManifestRepository.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/networking/FakeFinancialConnectionsManifestRepository.kt
Labels: work-cli

#8976 Update CHANGELOG update step to be idempotent
  scripts/deploy/update_version_numbers.rb
Labels: release-process-improvement

#8982 Add permissions check for release process
  scripts/deploy/add_new_team_member.rb
  scripts/deploy/common.rb
  scripts/deploy/deploy.rb
  scripts/deploy/permissions_check.rb
  scripts/deploy/run_permissions_check.rb
Labels: release-process-improvement

#8972 [NME] Accepting and sending new api param for acquiring consent for networking manual entry consent
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsPlaygroundViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/domain/SelectNetworkedAccounts.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerPreviewParameterProvider.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkstepupverification/LinkStepUpVerificationViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/success/SuccessContent.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/model/NetworkedAccountsList.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/repository/FinancialConnectionsAccountsRepository.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/linkstepupverification/LinkStepUpVerificationViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/networking/AbsFinancialConnectionsAccountsRepository.kt
Labels: work-cli

#8967 [NME] Pass `consumerSessionClientSecret` on Manual Entry Attach call
  financial-connections/src/main/java/com/stripe/android/financialconnections/domain/PollAttachPaymentAccount.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/attachpayment/AttachPaymentViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/manualentry/ManualEntryViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/repository/ConsumerSessionRepository.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/domain/PollAttachPaymentAccountTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/manualentry/ManualEntryViewModelTest.kt
Labels: work-cli
