Repository stripe/stripe-android, pull requests merged in 2024-10, with the labels that each got.

#9388 Delete basic integration CustomerSession from examples
  example/AndroidManifest.xml
  example/src/androidTestDebug/java/com/stripe/example/activity/AddFpxPaymentMethodTest.kt
  example/src/androidTestDebug/java/com/stripe/example/activity/AddNetbankingPaymentMethodTest.kt
  example/src/main/java/com/stripe/example/ExampleApplication.kt
  example/src/main/java/com/stripe/example/activity/CustomerSessionActivity.kt
  example/src/main/java/com/stripe/example/activity/LauncherActivity.kt
  example/src/main/java/com/stripe/example/service/ExampleEphemeralKeyProvider.kt
Labels: basic-integration-deprecation

#9403 Add analytics for vertical mode.
  paymentsheet/src/main/java/com/stripe/android/common/analytics/AnalyticsKtx.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEvent.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEventTest.kt
Labels: vertical-mode

#9389 Delete AddPaymentMethodActivity from examples
  example/AndroidManifest.xml
  example/src/androidTestDebug/java/com/stripe/example/activity/AddFpxPaymentMethodTest.kt
  example/src/androidTestDebug/java/com/stripe/example/activity/AddNetbankingPaymentMethodTest.kt
  example/src/main/java/com/stripe/example/activity/FpxPaymentActivity.java
  example/src/main/java/com/stripe/example/activity/LauncherActivity.kt
  example/src/main/java/com/stripe/example/activity/NetbankingListPaymentActivity.java
Labels: basic-integration-deprecation

#9402 Setup Firebase App Distribution for PaymentSheet.
  .github/workflows/push.yml
  paymentsheet-example/build.gradle
  paymentsheet-example/google-services.json
Labels: accept-risky-change

#9414 Add card brand filtering API
  payments-core/api/payments-core.api
  payments-core/src/main/java/com/stripe/android/CardBrandFilter.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/CardBrandAcceptanceSettingsDefinition.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/PlaygroundSettings.kt
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/ExperimentalCardBrandFilteringApi.kt
  paymentsheet/src/main/java/com/stripe/android/common/analytics/AnalyticsKtx.kt
  paymentsheet/src/main/java/com/stripe/android/common/configuration/ConfigurationDefaults.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheet.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/analytics/CustomerSheetEvent.kt
  paymentsheet/src/main/java/com/stripe/android/lpmfoundations/paymentmethod/PaymentSheetCardBrandFilter.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheet.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEvent.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetConfigurationTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/analytics/CustomerSheetEventTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetCardBrandFilterTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEventTest.kt
Labels: card brand filtering

#9441 [Verified Apps] Create `attestation` module.
  dependencies.gradle
  settings.gradle
  stripe-attestation/.gitignore
  stripe-attestation/api/stripe-attestation.api
  stripe-attestation/build.gradle
  stripe-attestation/dependencies/dependencies.txt
  stripe-attestation/gradle.properties
  stripe-attestation/src/main/AndroidManifest.xml
Labels: work-cli

#9453 Delete paymentsheet ActivityScenarioFactory.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PrimaryButtonTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/TestActivityRule.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/flowcontroller/FlowControllerFactoryTest.kt
  paymentsheet/src/test/java/com/stripe/android/view/ActivityScenarioFactory.kt
Labels: basic-integration-deprecation

#9456 Remove AddPaymentMethodActivity from ActivityScenarioFactory
  payments-core/src/test/java/com/stripe/android/auth/PaymentBrowserAuthContractTest.kt
  payments-core/src/test/java/com/stripe/android/view/ActivityScenarioFactory.kt
  payments-core/src/test/java/com/stripe/android/view/BecsDebitWidgetTest.kt
  payments-core/src/test/java/com/stripe/android/view/CardMultilineWidgetTest.kt
  payments-core/src/test/java/com/stripe/android/view/CardNumberEditTextTest.kt
  payments-core/src/test/java/com/stripe/android/view/CountryTextInputLayoutTest.kt
  payments-core/src/test/java/com/stripe/android/view/PaymentAuthWebViewTest.kt
  payments-core/src/test/java/com/stripe/android/view/ViewWidthAnimatorTest.kt
Labels: basic-integration-deprecation

#9461 Remove BI references from PaymentMethodCreateParamsTest
  payments-core/src/test/java/com/stripe/android/model/PaymentMethodCreateParamsTest.kt
Labels: basic-integration-deprecation

#9460 Remove BI references from PaymentAuthConfigTest
  payments-core/src/test/java/com/stripe/android/PaymentAuthConfigTest.kt
Labels: basic-integration-deprecation

#9463 Remove BI references from CardMultilineWidgetTest
  payments-core/src/test/java/com/stripe/android/view/CardMultilineWidgetTest.kt
Labels: basic-integration-deprecation

#9462 Remove BI references from PostalCodeEditTextTest
  payments-core/src/test/java/com/stripe/android/view/PostalCodeEditTextTest.kt
Labels: basic-integration-deprecation

#9458 Prepare for future import location change in lifecycle.
  example/dependencies/dependencies.txt
  financial-connections-example/dependencies/dependencies.txt
  identity-example/build.gradle
  identity-example/src/main/java/com/stripe/android/identity/example/ui/ComposeExampleUI.kt
  identity/build.gradle
  identity/dependencies/dependencies.txt
  identity/src/main/java/com/stripe/android/identity/ui/DocumentScanScreen.kt
  identity/src/main/java/com/stripe/android/identity/ui/SelfieScreen.kt
  identity/src/test/java/com/stripe/android/identity/ui/LiveCaptureLaunchedEffectTest.kt
  link/dependencies/dependencies.txt
  network-testing/dependencies/dependencies.txt
  payment-method-messaging/dependencies/dependencies.txt
  payments-core-testing/dependencies/dependencies.txt
  payments-core/build.gradle
  payments-core/dependencies/dependencies.txt
  payments-core/src/main/java/com/stripe/android/googlepaylauncher/GooglePayLauncher.kt
  payments-core/src/main/java/com/stripe/android/googlepaylauncher/GooglePayPaymentMethodLauncher.kt
  payments-ui-core/dependencies/dependencies.txt
  payments/dependencies/dependencies.txt
  paymentsheet-example/dependencies/dependencies.txt
  paymentsheet/build.gradle
  paymentsheet/dependencies/dependencies.txt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetCompose.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/FlowControllerCompose.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetCompose.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingScreen.kt
  stripe-connect-example/dependencies/dependencies.txt
  stripe-test-e2e/dependencies/dependencies.txt
  wechatpay/dependencies/dependencies.txt
Labels: accept-risky-change

#9481 Update PaymentSheet Example app to compose 1.7.4.
  paymentsheet-example/build.gradle
  paymentsheet-example/dependencies/dependencies.txt
Labels: accept-risky-change

#9484 Revert "Prepare for future import location change in lifecycle."
  example/dependencies/dependencies.txt
  financial-connections-example/dependencies/dependencies.txt
  identity-example/build.gradle
  identity-example/src/main/java/com/stripe/android/identity/example/ui/ComposeExampleUI.kt
  identity/build.gradle
  identity/dependencies/dependencies.txt
  identity/src/main/java/com/stripe/android/identity/ui/DocumentScanScreen.kt
  identity/src/main/java/com/stripe/android/identity/ui/SelfieScreen.kt
  identity/src/test/java/com/stripe/android/identity/ui/LiveCaptureLaunchedEffectTest.kt
  link/dependencies/dependencies.txt
  network-testing/dependencies/dependencies.txt
  payment-method-messaging/dependencies/dependencies.txt
  payments-core-testing/dependencies/dependencies.txt
  payments-core/build.gradle
  payments-core/dependencies/dependencies.txt
  payments-core/src/main/java/com/stripe/android/googlepaylauncher/GooglePayLauncher.kt
  payments-core/src/main/java/com/stripe/android/googlepaylauncher/GooglePayPaymentMethodLauncher.kt
  payments-ui-core/dependencies/dependencies.txt
  payments/dependencies/dependencies.txt
  paymentsheet-example/dependencies/dependencies.txt
  paymentsheet/build.gradle
  paymentsheet/dependencies/dependencies.txt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetCompose.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/FlowControllerCompose.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetCompose.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingScreen.kt
  stripe-test-e2e/dependencies/dependencies.txt
  wechatpay/dependencies/dependencies.txt
Labels: accept-risky-change

#9492 Remove --tag flag from tag push command
  scripts/deploy/create_github_release.rb
Labels: release-process-improvement

#9491 Remove BI references from StripeColorUtilsTest
  payments-core/src/test/java/com/stripe/android/view/StripeColorUtilsTest.kt
Labels: basic-integration-deprecation

#9497 Remove BI references from RadarSessionTest
  payments-core/src/androidTest/java/com/stripe/android/RadarSessionTest.kt
Labels: basic-integration-deprecation

#9495 Remove BI references from ShippingInfoWidgetTest
  payments-core/src/test/java/com/stripe/android/view/ShippingInfoWidgetTest.kt
Labels: basic-integration-deprecation

#9496 Remove BI references from CountryTextInputLayoutTest
  payments-core/src/test/java/com/stripe/android/view/CountryTextInputLayoutTest.kt
Labels: basic-integration-deprecation

#9475 Card brand filtering metrics
  payments-ui-core/src/main/java/com/stripe/android/ui/core/elements/CardNumberController.kt
  payments-ui-core/src/main/java/com/stripe/android/ui/core/elements/events/CardBrandDisallowedReporter.kt
  payments-ui-core/src/test/java/com/stripe/android/ui/core/elements/CardNumberControllerTest.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewAction.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/analytics/CustomerSheetEvent.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/analytics/CustomerSheetEventReporter.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/analytics/DefaultCustomerSheetEventReporter.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/ui/CustomerSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/lpmfoundations/paymentmethod/PaymentSheetCardBrandFilter.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/DefaultEventReporter.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/EventReporter.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEvent.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetScreen.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetEventReporterTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/analytics/DefaultEventReporterTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/analytics/FakeEventReporter.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeFormUITest.kt
Labels: card brand filtering

#9507 Prepare for future import location change in lifecycle.
  example/dependencies/dependencies.txt
  financial-connections-example/dependencies/dependencies.txt
  identity-example/build.gradle
  identity-example/src/main/java/com/stripe/android/identity/example/ui/ComposeExampleUI.kt
  identity/build.gradle
  identity/dependencies/dependencies.txt
  identity/src/main/java/com/stripe/android/identity/ui/DocumentScanScreen.kt
  identity/src/main/java/com/stripe/android/identity/ui/SelfieScreen.kt
  identity/src/test/java/com/stripe/android/identity/ui/LiveCaptureLaunchedEffectTest.kt
  link/dependencies/dependencies.txt
  network-testing/dependencies/dependencies.txt
  payment-method-messaging/dependencies/dependencies.txt
  payments-core-testing/dependencies/dependencies.txt
  payments-core/build.gradle
  payments-core/dependencies/dependencies.txt
  payments-core/src/main/java/com/stripe/android/googlepaylauncher/GooglePayLauncher.kt
  payments-core/src/main/java/com/stripe/android/googlepaylauncher/GooglePayPaymentMethodLauncher.kt
  payments-ui-core/dependencies/dependencies.txt
  payments/dependencies/dependencies.txt
  paymentsheet-example/dependencies/dependencies.txt
  paymentsheet/build.gradle
  paymentsheet/dependencies/dependencies.txt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetCompose.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/FlowControllerCompose.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetCompose.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingScreen.kt
  stripe-test-e2e/dependencies/dependencies.txt
  wechatpay/dependencies/dependencies.txt
Labels: accept-risky-change

#9500 Card brand filtering E2E tests
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/EditPage.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/FormPage.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/VerticalModePaymentSheetActivityTest.kt
Labels: card brand filtering

#9510 [Android] Success pane: "Almost there" copy for microdeposits
  financial-connections/res/values/strings.xml
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/manualentry/ManualEntryViewModel.kt
Labels: work-cli

#9533 Delete FPX bank icons
  payments-core/res/drawable/stripe_ic_bank_affin.xml
  payments-core/res/drawable/stripe_ic_bank_alliance.xml
  payments-core/res/drawable/stripe_ic_bank_ambank.xml
  payments-core/res/drawable/stripe_ic_bank_bsn.xml
  payments-core/res/drawable/stripe_ic_bank_cimb.xml
  payments-core/res/drawable/stripe_ic_bank_hong_leong.xml
  payments-core/res/drawable/stripe_ic_bank_hsbc.xml
  payments-core/res/drawable/stripe_ic_bank_islam.xml
  payments-core/res/drawable/stripe_ic_bank_kfh.xml
  payments-core/res/drawable/stripe_ic_bank_maybank.xml
  payments-core/res/drawable/stripe_ic_bank_muamalat.xml
  payments-core/res/drawable/stripe_ic_bank_ocbc.xml
  payments-core/res/drawable/stripe_ic_bank_public.xml
  payments-core/res/drawable/stripe_ic_bank_raykat.xml
  payments-core/res/drawable/stripe_ic_bank_rhb.xml
  payments-core/res/drawable/stripe_ic_bank_standard_chartered.xml
  payments-core/res/drawable/stripe_ic_bank_uob.xml
  payments-core/src/main/java/com/stripe/android/model/PaymentMethod.kt
  payments-core/src/main/java/com/stripe/android/view/Bank.kt
  payments-core/src/main/java/com/stripe/android/view/FpxBank.kt
  payments-core/src/main/java/com/stripe/android/view/NetbankingBank.kt
Labels: basic-integration-deprecation
