Repository stripe/stripe-android, pull requests merged in 2024-09, with the labels that each got.

#9155 On manage one PM screen, don't display the saved PM as selected
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageOneSavedPaymentMethodUI.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/VerticalModePaymentSheetActivityTest.kt
Labels: vertical-mode

#9182 Add full screen screenshot tests for ManageSavedPaymentMethods.
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreenManageSavedPaymentMethodsScreenshotTest.kt
  paymentsheet/src/test/snapshots/images/com.stripe.android.paymentsheet.navigation_PaymentSheetScreenManageSavedPaymentMethodsScreenshotTest_displaysEditMode[].png
  paymentsheet/src/test/snapshots/images/com.stripe.android.paymentsheet.navigation_PaymentSheetScreenManageSavedPaymentMethodsScreenshotTest_displaysSelectMode[].png
Labels: vertical-mode

#9181 Add full screen screenshot tests for CvcRecollection.
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreenCvcRecollectionScreenshotTest.kt
  paymentsheet/src/test/snapshots/images/com.stripe.android.paymentsheet.navigation_PaymentSheetScreenCvcRecollectionScreenshotTest_displaysCvcRecollectionScreen[].png
Labels: vertical-mode

#9183 Add full screen screenshot tests for ManageOneSavedPaymentMethod.
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreenManageOneSavedPaymentMethodScreenshotTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/FakeManageOneSavedPaymentMethodInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/ManageOneSavedPaymentMethodUITest.kt
  paymentsheet/src/test/snapshots/images/com.stripe.android.paymentsheet.navigation_PaymentSheetScreenManageOneSavedPaymentMethodScreenshotTest_displaysRemoveMode[].png
Labels: vertical-mode

#9160 [Android][ir-magnesium-presser] Clear cached accounts after manual entry enter succeeds
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/manualentry/ManualEntryViewModel.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/accountpicker/AccountPickerViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/manualentry/ManualEntryViewModelTest.kt
Labels: work-cli

#9146 [Connections] Playground - Adds Payment Element entry point
  financial-connections-example/build.gradle
  financial-connections-example/dependencies/dependencies.txt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsPlaygroundActivity.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsPlaygroundViewModel.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/data/model/CreateIntentResponse.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/settings/FlowSetting.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/settings/SettingsUi.kt
Labels: accept-risky-change

#9159 [Android] Add e2e tests with connected accounts
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/FinancialConnectionsPlaygroundViewModel.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/data/model/LinkAccountSessionBody.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/data/model/PaymentIntentBody.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/settings/PlaygroundSettings.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/settings/SettingsUi.kt
  financial-connections-example/src/main/java/com/stripe/android/financialconnections/example/settings/StripeAccountIdSetting.kt
  maestro/financial-connections/Testmode-Data-TestOauthInstitution-Connected.yaml
Labels: work-cli

#9196 Fix mandates in vertical mode.
  payments-core-testing/detekt-baseline.xml
  payments-core-testing/src/main/java/com/stripe/android/testing/PaymentMethodFactory.kt
  paymentsheet/detekt-baseline.xml
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/navigation/PaymentSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/viewmodels/BaseSheetViewModel.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/VerticalModePage.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/VerticalModePaymentSheetActivityTest.kt
Labels: vertical-mode

#9095 Remove hardcoded nature of afterpay payment calculation.
  payments-ui-core/src/main/java/com/stripe/android/ui/core/elements/AfterpayClearpayHeaderElement.kt
  payments-ui-core/src/main/java/com/stripe/android/ui/core/elements/AfterpayClearpayTextSpec.kt
  payments-ui-core/src/test/java/com/stripe/android/ui/core/elements/AfterpayClearpayHeaderElementTest.kt
  paymentsheet/src/main/java/com/stripe/android/lpmfoundations/luxe/TransformSpecToElements.kt
  paymentsheet/src/main/java/com/stripe/android/lpmfoundations/paymentmethod/UiDefinitionFactory.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/addresselement/FormControllerModule.kt
  paymentsheet/src/test/java/com/stripe/android/lpmfoundations/luxe/FormElementsBuilderTest.kt
  paymentsheet/src/test/java/com/stripe/android/lpmfoundations/luxe/TransformSpecToElementsTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/addresselement/FormControllerTest.kt
Labels: vertical-mode

#9201 Fix a bug where the selection would be cleared in flow controller.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultPaymentMethodVerticalLayoutInteractorTest.kt
Labels: vertical-mode

#9203 Set up Connect SDK Module
  .github/CODEOWNERS
  build.gradle
  settings.gradle
  stripe-connect-example/.gitignore
  stripe-connect-example/build.gradle
  stripe-connect-example/dependencies/dependencies.txt
  stripe-connect-example/detekt-baseline.xml
  stripe-connect-example/gradle.properties
  stripe-connect-example/src/main/AndroidManifest.xml
  stripe-connect-example/src/main/java/com/stripe/android/connectsdk/example/MainActivity.kt
  stripe-connect/.gitignore
  stripe-connect/api/stripe-connect.api
  stripe-connect/build.gradle
  stripe-connect/dependencies/dependencies.txt
  stripe-connect/detekt-baseline.xml
  stripe-connect/gradle.properties
  stripe-connect/src/main/AndroidManifest.xml
  stripe-connect/src/main/java/com/stripe/android/connectsdk/EmbeddedComponentActivity.kt
  stripe-connect/src/main/java/com/stripe/android/connectsdk/EmbeddedComponentManager.kt
  stripe-connect/src/main/java/com/stripe/android/connectsdk/PrivateBetaConnectSDK.kt
Labels: accept-risky-change

#9207 Navigate to form screen in flow controller for current selections.
  payments-ui-core/detekt-baseline.xml
  paymentsheet/detekt-baseline.xml
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/FormHelper.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeInitialScreenFactory.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/FormHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultPaymentMethodVerticalLayoutInteractorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeInitialScreenFactoryTest.kt
Labels: vertical-mode

#9217 Add integration tests for FlowController in vertical mode.
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/FlowControllerTest.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/PaymentSheetPage.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/utils/FlowControllerTestFactory.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/utils/FlowControllerTestRunner.kt
Labels: vertical-mode

#9224 Add a test for vertical mode analytics.
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/PaymentSheetAnalyticsTest.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/utils/FlowControllerTestRunner.kt
Labels: vertical-mode

#9055 Add NME e2e test
  bitrise.yml
  maestro/financial-connections/Testmode-Token-ManualEntry.yaml
  maestro/financial-connections/Testmode-Token-NME.yaml
  scripts/execute_maestro_tests.sh
Labels: work-cli

#9001 Update Emerge tools integration to use latest best practices
  .github/workflows/ci.yml
  .github/workflows/financialconnections_pull_request.yml
  .github/workflows/identity_pull_request.yml
  .github/workflows/push.yml
  build.gradle
  financial-connections-example/build.gradle
  identity-example/build.gradle
  paymentsheet-example/build.gradle
Labels: accept-risky-change

#9292 Only push specific tag.
  scripts/deploy/create_github_release.rb
Labels: release-process-improvement

#9250 Expose vertical mode for private beta.
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ExperimentalPaymentMethodLayoutApi.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheet.kt
Labels: vertical-mode

#9282 Restore `PlaygroundState` after process death
  paymentsheet-example/build.gradle
  paymentsheet-example/dependencies/dependencies.txt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/PaymentSheetPlaygroundViewModel.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/PlaygroundState.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/PlaygroundConfigurationData.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/PlaygroundSettings.kt
Labels: accept-risky-change

#9309 Scroll to the top of the current screen.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetScaffold.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetScreen.kt
Labels: vertical-mode

#9315 Do not do another Consumer lookup when initiating step-up authentication
  financial-connections/src/main/java/com/stripe/android/financialconnections/domain/GetCachedConsumerSession.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/accountpicker/AccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/linkstepupverification/LinkStepUpVerificationViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/networkinglinkverification/NetworkingLinkVerificationViewModel.kt
  financial-connections/src/main/java/com/stripe/android/financialconnections/features/networkingsavetolinkverification/NetworkingSaveToLinkVerificationViewModel.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/ApiKeyFixtures.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/accountpicker/AccountPickerViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/linkaccountpicker/LinkAccountPickerViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/linkstepupverification/LinkStepUpVerificationViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/networkinglinkverification/NetworkingLinkVerificationViewModelTest.kt
  financial-connections/src/test/java/com/stripe/android/financialconnections/features/networkingsavetolinkverification/NetworkingSaveToLinkVerificationViewModelTest.kt
Labels: work-cli

#9342 Add explicit dependency on material icons for modules that use it.
  example/build.gradle
  example/dependencies/dependencies.txt
  financial-connections-example/build.gradle
  financial-connections-example/dependencies/dependencies.txt
  financial-connections/build.gradle
  financial-connections/dependencies/dependencies.txt
  identity-example/build.gradle
  identity/dependencies/dependencies.txt
  link/dependencies/dependencies.txt
  network-testing/dependencies/dependencies.txt
  payment-method-messaging/dependencies/dependencies.txt
  payments-core-testing/dependencies/dependencies.txt
  payments-core/dependencies/dependencies.txt
  payments-ui-core/dependencies/dependencies.txt
  payments/dependencies/dependencies.txt
  paymentsheet-example/dependencies/dependencies.txt
  paymentsheet/dependencies/dependencies.txt
  screenshot-testing/dependencies/dependencies.txt
  stripe-test-e2e/dependencies/dependencies.txt
  stripe-ui-core/build.gradle
  stripe-ui-core/dependencies/dependencies.txt
  wechatpay/dependencies/dependencies.txt
Labels: accept-risky-change

#9353 Add Automatic as a PaymentMethodLayout enum option.
  paymentsheet-example/src/androidTest/java/com/stripe/android/lpm/TestVerticalMode.kt
  paymentsheet-example/src/androidTest/java/com/stripe/android/test/core/PlaygroundTestDriver.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/LayoutSettingsDefinition.kt
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/MandateHandler.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheet.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModelCvcHelper.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentOptionsViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetViewModelTest.kt
Labels: vertical-mode

#9359 Only select selection in manage screen.
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/FlowControllerTest.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenInteractor.kt
Labels: vertical-mode
