Repository stripe/stripe-android, pull requests merged in 2025-09, with the labels that each got.

#11511 Add TestPayNow
  paymentsheet-example/src/androidTest/java/com/stripe/android/lpm/TestPayNow.kt
  paymentsheet-example/src/androidTest/java/com/stripe/android/test/core/PlaygroundTestDriver.kt
  paymentsheet-example/src/androidTest/java/com/stripe/android/test/core/TestParameters.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/EnablePayNowSettingsDefinition.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/FeatureFlagSettingsDefinition.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/PlaygroundSettings.kt
Labels: PayNow

#11537 Use Gradle managed devices for `run-instrumentation-tests` pipeline
  bitrise.yml
  build-configuration/android-application.gradle
  build-configuration/android-library.gradle
  connect-example/build.gradle
  connect/build.gradle
  connect/src/androidTest/java/com/stripe/android/connect/StripeConnectRedirectActivityTest.kt
  gradle.properties
  paymentsheet/build.gradle
Labels: accept-risky-change

#11553 Add ConfirmationToken model and JSON parsers
  payments-core/api/payments-core.api
  payments-core/src/main/java/com/stripe/android/model/ConfirmationToken.kt
  payments-core/src/main/java/com/stripe/android/model/MandateData.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/ConfirmationTokenJsonParser.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/MandateDataJsonParser.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/PaymentMethodPreviewJsonParser.kt
  payments-core/src/test/java/com/stripe/android/model/ConfirmationTokenFixtures.kt
  payments-core/src/test/java/com/stripe/android/model/parsers/ConfirmationTokenJsonParserTest.kt
  payments-core/src/test/java/com/stripe/android/model/parsers/MandateDataJsonParserTest.kt
  payments-core/src/test/java/com/stripe/android/model/parsers/PaymentMethodPreviewJsonParserTest.kt
Labels: ConfirmationToken

#11595 [Identity] Fix identity upload file state is not being reset when activity gets re-created
  identity/src/main/java/com/stripe/android/identity/viewmodel/IdentityViewModel.kt
Labels: identity

#11545 Create ConfirmationTokens with ConfirmationTokenParams
  payments-core-testing/src/main/java/com/stripe/android/testing/AbsFakeStripeRepository.kt
  payments-core/src/main/java/com/stripe/android/Stripe.kt
  payments-core/src/main/java/com/stripe/android/networking/StripeApiRepository.kt
  payments-core/src/main/java/com/stripe/android/networking/StripeRepository.kt
  payments-core/src/test/java/com/stripe/android/networking/StripeApiRepositoryTest.kt
Labels: ConfirmationToken

#11597 Send Analytics Event for Confirmation Creation
  payments-core/src/main/java/com/stripe/android/networking/PaymentAnalyticsEvent.kt
  payments-core/src/main/java/com/stripe/android/networking/StripeApiRepository.kt
  payments-core/src/test/java/com/stripe/android/networking/StripeApiRepositoryTest.kt
Labels: ConfirmationToken

#11617 Add PaymentMethodSelectionFlow to ClientAttributionMetadata
  payments-core/api/payments-core.api
  payments-core/src/main/java/com/stripe/android/model/ClientAttributionMetadata.kt
  payments-core/src/main/java/com/stripe/android/model/PaymentIntent.kt
  payments-core/src/main/java/com/stripe/android/model/SetupIntent.kt
  payments-core/src/main/java/com/stripe/android/model/StripeIntent.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/DeferredPaymentIntentJsonParser.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/DeferredSetupIntentJsonParser.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/PaymentIntentJsonParser.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/SetupIntentJsonParser.kt
  payments-core/src/test/java/com/stripe/android/model/ClientAttributionMetadataTest.kt
  payments-core/src/test/java/com/stripe/android/model/PaymentIntentFixtures.kt
  payments-core/src/test/java/com/stripe/android/model/SetupIntentFixtures.kt
  payments-core/src/test/java/com/stripe/android/model/parsers/PaymentIntentJsonParserTest.kt
  payments-core/src/test/java/com/stripe/android/model/parsers/SetupIntentJsonParserTest.kt
  paymentsheet/src/main/java/com/stripe/android/lpmfoundations/paymentmethod/ClientAttributionMetadataKtx.kt
  paymentsheet/src/main/java/com/stripe/android/lpmfoundations/paymentmethod/PaymentMethodMetadata.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/repositories/ElementsSessionRepository.kt
  paymentsheet/src/test/java/com/stripe/android/lpmfoundations/paymentmethod/ClientAttributionMetadataKtxTest.kt
  paymentsheet/src/test/java/com/stripe/android/lpmfoundations/paymentmethod/PaymentMethodMetadataTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/state/DefaultPaymentElementLoaderTest.kt
Labels: project-weave

#11621 Add CreateIntentWithConfirmationTokenCallback for PaymentSheet and FlowController
  paymentsheet/src/main/java/com/stripe/android/paymentelement/CreateIntentWithConfirmationTokenCallback.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/callbacks/PaymentElementCallbacks.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheet.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/callbacks/PaymentElementCallbacksTest.kt
Labels: ConfirmationToken

#11622 Add client attribution metadata for new US bank payments
  payments-core/api/payments-core.api
  payments-core/src/main/java/com/stripe/android/model/PaymentMethodCreateParams.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/PaymentSheetTest.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/utils/PaymentMethodType.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/utils/UsBankAccountFormTestUtils.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountForm.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountFormArguments.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountFormViewModel.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetScreenshotTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/paymentdatacollection/ach/USBankAccountFormViewModelTest.kt
Labels: project-weave

#11644 Add CreateIntentWithConfirmationTokenCallback for Embedded
  paymentsheet/src/androidTest/java/com/stripe/android/paymentelement/EmbeddedPaymentElementTestRunner.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/EmbeddedPaymentElement.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/EmbeddedPaymentElementKtx.kt
Labels: ConfirmationToken
