Repository stripe/stripe-android, pull requests merged in 2025-04, with the labels that each got.

#10560 Update UI to collect on the main thread to avoid compose crashes.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsActivity.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetActivity.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenUI.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodEmbeddedLayoutUI.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeFormUI.kt
Labels: flake-fix

#10562 Fix SPM flaky tests
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetViewModelTest.kt
Labels: flake-fix

#10561 Introduce a main thread state flow.
  camera-core/dependencies/dependencies.txt
  connect-example/dependencies/dependencies.txt
  connect/dependencies/dependencies.txt
  example/dependencies/dependencies.txt
  financial-connections-core/dependencies/dependencies.txt
  financial-connections-example/dependencies/dependencies.txt
  financial-connections-lite/dependencies/dependencies.txt
  financial-connections/dependencies/dependencies.txt
  identity/dependencies/dependencies.txt
  payment-method-messaging/dependencies/dependencies.txt
  payments-core/dependencies/dependencies.txt
  payments-model/dependencies/dependencies.txt
  payments-ui-core/dependencies/dependencies.txt
  payments/dependencies/dependencies.txt
  paymentsheet-example/dependencies/dependencies.txt
  paymentsheet/dependencies/dependencies.txt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/EmbeddedSelectionHolder.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/EmbeddedConfirmationStateHolder.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/EmbeddedContentHelper.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/PaymentOptionDisplayDataHolder.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormActivityStateHelper.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/EmbeddedSelectionHolderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedConfigurationCoordinatorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedConfirmationHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedContentHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSelectionChooserTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSheetLauncherTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedStateHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultPaymentOptionDisplayDataHolderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/EmbeddedConfirmationStateHolderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/DefaultFormActivityStateHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/FormActivityConfirmationHandlerTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/FormActivityScreenShotTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultPaymentMethodVerticalLayoutInteractorTest.kt
  stripe-core/build.gradle
  stripe-core/dependencies/dependencies.txt
  stripe-core/src/main/java/com/stripe/android/core/mainthread/MainThreadOnlyMutableStateFlow.kt
  stripe-core/src/main/java/com/stripe/android/core/mainthread/MainThreadSavedStateHandle.kt
  stripe-ui-core/dependencies/dependencies.txt
  stripecardscan-example/dependencies/dependencies.txt
  stripecardscan/dependencies/dependencies.txt
  wechatpay/dependencies/dependencies.txt
Labels: flake-fix

#10569 Add main thread state flow to vertical interactor.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
Labels: flake-fix

#10567 Introduce `PaymentSelection.CustomPaymentMethod`
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/ConfirmationOptionKtx.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/EmbeddedFormHelperFactory.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/EmbeddedSelectionChooser.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/PaymentOptionDisplayDataFactory.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/DefaultFormHelper.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/NewPaymentOptionSelection.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsStateFactory.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEvent.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/flowcontroller/DefaultFlowController.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/flowcontroller/PaymentSelectionUpdater.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/model/PaymentSelection.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/AddPaymentMethod.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/SelectSavedPaymentMethodsInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/viewmodels/BaseSheetViewModel.kt
  paymentsheet/src/test/java/com/stripe/android/model/PaymentMethodFixtures.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSelectionChooserTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/FakePrefsRepository.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/FormHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentOptionsViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEventTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/flowcontroller/PaymentSelectionUpdaterTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/ui/AddPaymentMethodTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/viewmodels/FakeBaseSheetViewModel.kt
Labels: custom-payment-methods

#10576 Ensure updating updating state happens on the main thread in PaymentSheet.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
Labels: flake-fix

#10578 Add retry to flakey tests.
  bitrise.yml
  scripts/retry.sh
Labels: flake-fix

#10596 Fix threading in SavedPaymentMethodMutator.
  payment-element-test-pages/src/main/java/com/stripe/paymentelementnetwork/PaymentMethodModificationExtensions.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentelement/EmbeddedPaymentElementTest.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutator.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/manage/ManageActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/VerticalModePaymentSheetActivityTest.kt
Labels: embedded

#10587 Release EmbeddedPaymentElement in private beta.
  CHANGELOG.md
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/paymentelement/EmbeddedPaymentElement.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/EmbeddedPaymentElementKtx.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/ExperimentalEmbeddedPaymentElementApi.kt
Labels: embedded

#10620 Add test for DefaultFormActivityConfirmationHelper.
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/DefaultFormActivityConfirmationHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/analytics/FakeEventReporter.kt
Labels: embedded

#10595 Introduce FormSheetAction public API for embedded.
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/EmbeddedFormSheetActionSettingDefinition.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/PlaygroundSettings.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/EmbeddedPaymentElement.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSheetLauncher.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormContract.kt
Labels: embedded

#10597 Implement FormSheetAction in embedded.
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSheetLauncher.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormActivity.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormActivityConfirmationHelper.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormActivityStateHelper.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormActivityUI.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormContract.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSheetLauncherTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/DefaultFormActivityConfirmationHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/DefaultFormActivityStateHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/FakeFormActivityStateHelper.kt
Labels: embedded

#10602 Update selection logic for formSheetAction=continue.
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSheetLauncher.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/EmbeddedContentHelper.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormActivityViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormActivityViewModelComponent.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormContract.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSheetLauncherTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/FormActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultPaymentMethodVerticalLayoutInteractorTest.kt
Labels: embedded

#10633 Add changeDetails to vertical selection.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/model/PaymentMethodFixtures.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultPaymentMethodVerticalLayoutInteractorTest.kt
Labels: embedded

#10634 Add embedded specific analytics.
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/EmbeddedConfigurationHandler.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/DefaultEventReporter.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/EventReporter.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEvent.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/flowcontroller/FlowControllerConfigurationHandler.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/analytics/DefaultEventReporterTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/analytics/FakeEventReporter.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEventTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/flowcontroller/FlowControllerConfigurationHandlerTest.kt
Labels: embedded

#10636 Select Saved PM in Horizontal PaymentSheet Should Send Analytic Events
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/PaymentSheetAnalyticsTest.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
Labels: analytic-event-framework

#10623 Add custom payment method confirmation
  payments-core/src/main/java/com/stripe/android/payments/core/analytics/ErrorReporter.kt
  paymentsheet-example/src/main/AndroidManifest.xml
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/PaymentSheetPlaygroundActivity.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/activity/CustomPaymentMethodActivity.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/embedded/EmbeddedPlaygroundActivity.kt
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/AndroidManifest.xml
  paymentsheet/src/main/java/com/stripe/android/paymentelement/CustomPaymentMethodResultHandler.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/ConfirmationOptionKtx.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodConfirmationDefinition.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodConfirmationModule.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodConfirmationOption.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodContract.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodInput.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodProxyActivity.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/cpms/InternalCustomPaymentMethodResult.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/injection/PaymentElementConfirmationModule.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/ConfirmationHandlerOptionKtxTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/ExtendedPaymentElementConfirmationOrderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/PaymentElementConfirmationOrderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodConfirmationActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodConfirmationDefinitionTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodContractTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/cpms/CustomPaymentMethodProxyActivityTest.kt
Labels: custom-payment-methods

#10646 Implement 2 step flow for embedded.
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/PaymentSheetPlaygroundActivity.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/PaymentSheetPlaygroundViewModel.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/embedded/EmbeddedPlaygroundActivity.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/embedded/EmbeddedPlaygroundOneStepContract.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/embedded/EmbeddedPlaygroundTwoStepContract.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/EmbeddedTwoStepSettingsDefinition.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/PlaygroundSettings.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentelement/EmbeddedContentPage.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentelement/EmbeddedPaymentElementTest.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentelement/EmbeddedPaymentElementTestRunner.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/EmbeddedPaymentElement.kt
Labels: embedded

#10650 Add emulator tests for Custom Payment Methods
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/CustomPaymentMethodsTest.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/PaymentSheetPage.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentsheet/utils/ProductIntegrationTestRunner.kt
  paymentsheet/src/androidTest/resources/elements-sessions-cpms.json
Labels: custom-payment-methods

#10654 Fix onRemoveSavedPaymentMethod does not correctly send when no PM is selected
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutator.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutatorTest.kt
Labels: analytic-event-framework

#10652 Expose embedded appearance API.
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheet.kt
Labels: embedded

#10656 FormSheetAction integration tests.
  paymentsheet/src/androidTest/java/com/stripe/android/paymentelement/EmbeddedContentPage.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentelement/EmbeddedPaymentElementTest.kt
Labels: embedded

#10661 Fix a threading issue for PaymentSheetViewModel.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetViewModel.kt
Labels: flake-fix

#10660 Add E2E tests for Custom Payment Methods
  paymentsheet-example/src/androidTest/java/com/stripe/android/lpm/TestCustomPaymentMethod.kt
  paymentsheet-example/src/androidTest/java/com/stripe/android/test/core/PlaygroundTestDriver.kt
  paymentsheet-example/src/androidTest/java/com/stripe/android/test/core/ui/Selectors.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/activity/CustomPaymentMethodActivity.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/CustomPaymentMethodsSettingsDefinition.kt
Labels: custom-payment-methods

#10662 Fix a threading issue for SavedPaymentMethodMutator.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutator.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/PaymentOptionsViewModelTest.kt
Labels: flake-fix

#10658 Update link account on the main thread.
  paymentsheet/src/main/java/com/stripe/android/link/account/DefaultLinkAccountManager.kt
  paymentsheet/src/main/java/com/stripe/android/link/account/LinkAccountManager.kt
  paymentsheet/src/test/java/com/stripe/android/link/account/DefaultLinkAccountManagerTest.kt
  paymentsheet/src/test/java/com/stripe/android/link/account/FakeLinkAccountManager.kt
Labels: flake-fix

#10667 Add retries to instrumentation tests.
  bitrise.yml
Labels: flake-fix

#10663 Fix a threading issue for CustomerSheetViewModel.
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
  stripe-core/src/main/java/com/stripe/android/core/mainthread/MainThreadOnlyMutableStateFlow.kt
Labels: flake-fix

#10676 Force main thread in UpdatePaymentMethodInteractor.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/UpdatePaymentMethodInteractor.kt
Labels: flake-fix

#10692 Fix 2 more random threading issues.
  payments-core/src/main/java/com/stripe/android/cards/RemoteCardAccountRangeSource.kt
  payments-core/src/test/java/com/stripe/android/cards/DefaultCardAccountRangeRepositoryTest.kt
  payments-core/src/test/java/com/stripe/android/cards/RemoteCardAccountRangeSourceTest.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
Labels: flake-fix

#10698 Fix some playground threading issues with CustomerSheet.
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/PaymentSheetPlaygroundActivity.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/PaymentSheetPlaygroundViewModel.kt
Labels: flake-fix

#10699 Fix threading issues in PollingViewModel.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingViewModel.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingTestUtils.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingViewModelTest.kt
Labels: flake-fix

#10695 Enforce main thread in collectAsState.
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/PaymentSheetPlaygroundViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetActivity.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/ui/CustomerSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentOptionsActivity.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetActivity.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/AddPaymentMethod.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/ui/PaymentSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/ManageScreenUI.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodEmbeddedLayoutUI.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/VerticalModeFormUI.kt
  stripe-ui-core/src/main/java/com/stripe/android/uicore/utils/StateFlowsCompose.kt
Labels: flake-fix

#10700 Remove temporary main thread utilities.
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/EmbeddedSelectionHolder.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/EmbeddedConfirmationStateHolder.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/EmbeddedContentHelper.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/EmbeddedPaymentElementInitializer.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/EmbeddedSelectionChooser.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/content/PaymentOptionDisplayDataHolder.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/form/FormActivityStateHelper.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/SavedPaymentMethodMutator.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/EmbeddedSelectionHolderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedConfigurationCoordinatorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedConfirmationHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedContentHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSelectionChooserTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedSheetLauncherTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultEmbeddedStateHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/DefaultPaymentOptionDisplayDataHolderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/EmbeddedConfirmationStateHolderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/content/EmbeddedPaymentElementInitializerTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/DefaultFormActivityConfirmationHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/DefaultFormActivityStateHelperTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/FormActivityConfirmationHandlerTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/embedded/form/FormActivityScreenShotTest.kt
  stripe-core/src/main/java/com/stripe/android/core/mainthread/MainThreadOnlyMutableStateFlow.kt
  stripe-core/src/main/java/com/stripe/android/core/mainthread/MainThreadSavedStateHandle.kt
Labels: flake-fix

#10729 Implement change UI bug fixes.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodEmbeddedLayoutUI.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultPaymentMethodVerticalLayoutInteractorTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodEmbeddedLayoutUIScreenshotTest.kt
  paymentsheet/src/test/snapshots/images/com.stripe.android.paymentsheet.verticalmode_PaymentMethodEmbeddedLayoutUIScreenshotTest_testNewPaymentMethodsWithSelectionWithoutChangeDetails[CrazyAppearance].png
  paymentsheet/src/test/snapshots/images/com.stripe.android.paymentsheet.verticalmode_PaymentMethodEmbeddedLayoutUIScreenshotTest_testNewPaymentMethodsWithSelectionWithoutChangeDetails[CustomAppearance].png
  paymentsheet/src/test/snapshots/images/com.stripe.android.paymentsheet.verticalmode_PaymentMethodEmbeddedLayoutUIScreenshotTest_testNewPaymentMethodsWithSelectionWithoutChangeDetails[DefaultAppearance].png
Labels: embedded

#10730 Remove should not clear current selection.
  paymentsheet/src/androidTest/java/com/stripe/android/paymentelement/EmbeddedContentPage.kt
  paymentsheet/src/androidTest/java/com/stripe/android/paymentelement/EmbeddedPaymentElementTest.kt
  paymentsheet/src/androidTest/resources/elements-sessions-deferred_payment_intent_no_link.json
  paymentsheet/src/main/java/com/stripe/android/paymentelement/embedded/manage/ManageSavedPaymentMethodMutatorFactory.kt
Labels: embedded

#10720 Expose embedded state and FormSheetAction.
  CHANGELOG.md
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/paymentelement/EmbeddedPaymentElement.kt
Labels: embedded

#10741 Fix change details logic when a saved card is currently selected.
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/verticalmode/PaymentMethodVerticalLayoutInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/verticalmode/DefaultPaymentMethodVerticalLayoutInteractorTest.kt
Labels: embedded

#10733 Enable `Custom Payment Methods` for private beta.
  CHANGELOG.md
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/paymentelement/ConfirmCustomPaymentMethodCallback.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/CustomPaymentMethodResultHandler.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/EmbeddedPaymentElement.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheet.kt
Labels: custom-payment-methods

#10651 Remove Group Restriction Annotation on Analytic Event
  CHANGELOG.md
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/java/com/stripe/android/paymentelement/AnalyticEventCallback.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/EmbeddedPaymentElement.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/ExperimentalAnalyticEventCallbackApi.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheet.kt
Labels: DO-NOT-MERGE, analytic-event-framework

#10738 Add `Sentry` analytics to `paymentsheet-example`
  bitrise.yml
  build.gradle
  dependencies.gradle
  paymentsheet-example/build.gradle
  paymentsheet-example/dependencies/dependencies.txt
  paymentsheet-example/src/main/AndroidManifest.xml
Labels: accept-risky-change
