Repository stripe/stripe-android, pull requests merged in 2025-08, with the labels that each got.

#11240 Add passive captcha parameters to Elements session
  payments-core/api/payments-core.api
  payments-core/src/main/java/com/stripe/android/model/ElementsSession.kt
  payments-core/src/main/java/com/stripe/android/model/PassiveCaptchaParams.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/ElementsSessionJsonParser.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/PassiveCaptchaJsonParser.kt
  payments-core/src/test/java/com/stripe/android/model/ElementsSessionFixtures.kt
  payments-core/src/test/java/com/stripe/android/model/ElementsSessionTest.kt
  payments-core/src/test/java/com/stripe/android/model/parsers/ElementsSessionJsonParserTest.kt
  payments-core/src/test/java/com/stripe/android/model/parsers/PassiveCaptchaJsonParserTest.kt
  paymentsheet/src/test/java/com/stripe/android/common/analytics/experiment/LogLinkGlobalHoldbackExposureTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetFixtures.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/data/FakeCustomerSessionElementsSessionManager.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/state/DefaultCustomerSheetLoaderTest.kt
  paymentsheet/src/test/java/com/stripe/android/lpmfoundations/paymentmethod/PaymentMethodMetadataTest.kt
  paymentsheet/src/test/java/com/stripe/android/utils/FakeElementsSessionRepository.kt
Labels: challenge

#11262 StripeCryptoOnramp: Onramp Example App
  paymentsheet-example/build.gradle
  paymentsheet-example/dependencies/dependencies.txt
  paymentsheet-example/src/main/AndroidManifest.xml
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/MainActivity.kt
  settings.gradle
  stripe-crypto-onramp-example/.gitignore
  stripe-crypto-onramp-example/api/stripe-crypto-onramp-example.api
  stripe-crypto-onramp-example/build.gradle
  stripe-crypto-onramp-example/dependencies/dependencies.txt
  stripe-crypto-onramp-example/gradle.properties
  stripe-crypto-onramp-example/proguard-rules.pro
  stripe-crypto-onramp-example/src/androidTest/java/com/stripe/android/crypto/onramp/example/ExampleInstrumentedTest.kt
  stripe-crypto-onramp-example/src/main/AndroidManifest.xml
  stripe-crypto-onramp-example/src/main/ic_launcher-playstore.png
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/OnrampActivity.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/OnrampViewModel.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/ui/theme/Color.kt
  stripe-crypto-onramp-example/src/main/res/drawable/ic_launcher_background.xml
  stripe-crypto-onramp-example/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  stripe-crypto-onramp-example/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  stripe-crypto-onramp-example/src/main/res/mipmap-hdpi/ic_launcher.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-mdpi/ic_launcher.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-xhdpi/ic_launcher.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  stripe-crypto-onramp-example/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  stripe-crypto-onramp-example/src/main/res/values/colors.xml
  stripe-crypto-onramp-example/src/main/res/values/strings.xml
  stripe-crypto-onramp-example/src/main/res/values/themes.xml
Labels: accept-risky-change

#11268 Introduce Passive Challenge Confirmation Definition
  payments-core/src/main/java/com/stripe/android/payments/core/analytics/ErrorReporter.kt
  paymentsheet/api/paymentsheet.api
  paymentsheet/src/main/AndroidManifest.xml
  paymentsheet/src/main/java/com/stripe/android/challenge/PassiveChallengeActivity.kt
  paymentsheet/src/main/java/com/stripe/android/challenge/PassiveChallengeActivityContract.kt
  paymentsheet/src/main/java/com/stripe/android/challenge/PassiveChallengeActivityResult.kt
  paymentsheet/src/main/java/com/stripe/android/challenge/PassiveChallengeArgs.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/PaymentMethodConfirmationOption.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/challenge/PassiveChallengeConfirmationDefinition.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/challenge/PassiveChallengeConfirmationModule.kt
  paymentsheet/src/main/java/com/stripe/android/paymentelement/confirmation/injection/DefaultConfirmationModule.kt
  paymentsheet/src/test/java/com/stripe/android/challenge/PassiveChallengeActivityContractTest.kt
  paymentsheet/src/test/java/com/stripe/android/challenge/PassiveChallengeActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/ExtendedPaymentElementConfirmationOrderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/PaymentElementConfirmationOrderTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentelement/confirmation/challenge/PassiveChallengeConfirmationDefinitionTest.kt
Labels: challenge

#11343 StripeCryptoOnramp: Collect Payment Method
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/LinkControllerUi.kt
  paymentsheet/src/main/java/com/stripe/android/common/ui/DelegateDrawable.kt
  paymentsheet/src/main/java/com/stripe/android/link/LinkController.kt
  paymentsheet/src/main/java/com/stripe/android/link/LinkControllerInteractor.kt
  paymentsheet/src/test/java/com/stripe/android/link/LinkControllerCoordinatorTest.kt
  paymentsheet/src/test/java/com/stripe/android/link/LinkControllerInteractorTest.kt
  stripe-crypto-onramp-example/build.gradle
  stripe-crypto-onramp-example/dependencies/dependencies.txt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/OnrampActivity.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/OnrampViewModel.kt
  stripe-crypto-onramp/src/main/java/com/stripe/android/crypto/onramp/OnrampCoordinator.kt
  stripe-crypto-onramp/src/main/java/com/stripe/android/crypto/onramp/OnrampInteractor.kt
  stripe-crypto-onramp/src/main/java/com/stripe/android/crypto/onramp/OnrampPresenterCoordinator.kt
  stripe-crypto-onramp/src/main/java/com/stripe/android/crypto/onramp/model/OnrampCallbacks.kt
  stripe-crypto-onramp/src/main/java/com/stripe/android/crypto/onramp/model/OnrampSelectPaymentCallback.kt
Labels: accept-risky-change

#11405 Show polling screen when attempting to confirm PayNow
  payments-core/api/payments-core.api
  payments-core/src/main/java/com/stripe/android/StripeIntentResult.kt
  payments-core/src/main/java/com/stripe/android/model/PaymentIntent.kt
  payments-core/src/main/java/com/stripe/android/model/SetupIntent.kt
  payments-core/src/main/java/com/stripe/android/model/StripeIntent.kt
  payments-core/src/main/java/com/stripe/android/model/parsers/NextActionDataParser.kt
  paymentsheet/res/values/strings.xml
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/PaymentSheetNextActionHandlers.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingNextActionHandler.kt
Labels: PayNow

#11393 Init Card Scan Migration with Feature Flag
  payments-ui-core/src/main/java/com/stripe/android/ui/core/cardscan/CardScanGoogleLauncher.kt
  payments-ui-core/src/main/java/com/stripe/android/ui/core/cardscan/PaymentCardRecognitionClient.kt
  payments-ui-core/src/main/java/com/stripe/android/ui/core/elements/CardDetailsSectionElementUI.kt
  payments-ui-core/src/main/java/com/stripe/android/ui/core/elements/ScanCardButtonUI.kt
  payments-ui-core/src/test/java/com/stripe/android/ui/core/cardscan/CardScanGoogleLauncherTest.kt
  payments-ui-core/src/test/java/com/stripe/android/ui/core/cardscan/FakePaymentCardRecognitionClient.kt
  paymentsheet-example/src/main/java/com/stripe/android/paymentsheet/example/playground/settings/PlaygroundSettings.kt
  stripe-core/src/main/java/com/stripe/android/core/utils/FeatureFlags.kt
Labels: cardscan-migration

#11419 Deprecated stripecardscan Module Public APIs
  CHANGELOG.md
  MIGRATING.md
  stripecardscan/src/main/java/com/stripe/android/stripecardscan/cardscan/CardScanSheet.kt
  stripecardscan/src/main/java/com/stripe/android/stripecardscan/payment/card/ScannedCard.kt
  stripecardscan/src/main/java/com/stripe/android/stripecardscan/scanui/ScanActivity.kt
Labels: cardscan-migration

#11416 Show PayNow QR code
  payments-core/src/main/java/com/stripe/android/view/PaymentAuthWebView.kt
  payments-core/src/main/java/com/stripe/android/view/PaymentAuthWebViewClient.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingActivity.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingContract.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingNextActionHandler.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/QrCodeWebView.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingActivityTest.kt
  paymentsheet/src/test/java/com/stripe/android/paymentsheet/paymentdatacollection/polling/PollingViewModelTest.kt
Labels: PayNow

#11429 Fix missing validation
  payments-ui-core/src/test/java/com/stripe/android/ui/core/cardscan/CardScanGoogleLauncherTest.kt
Labels: cardscan-migration

#11428 Support CustomerSheet
  payments-ui-core/src/main/java/com/stripe/android/ui/core/cardscan/CardScanEventsReporter.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewAction.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/CustomerSheetViewModel.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/analytics/CustomerSheetEvent.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/analytics/CustomerSheetEventReporter.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/analytics/DefaultCustomerSheetEventReporter.kt
  paymentsheet/src/main/java/com/stripe/android/customersheet/ui/CustomerSheetScreen.kt
  paymentsheet/src/main/java/com/stripe/android/paymentsheet/analytics/PaymentSheetEvent.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetEventReporterTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/CustomerSheetViewModelTest.kt
  paymentsheet/src/test/java/com/stripe/android/customersheet/state/DefaultCustomerSheetLoaderTest.kt
  stripe-core/src/main/java/com/stripe/android/core/utils/DurationProvider.kt
Labels: cardscan-migration

#11427 [Onramp] Adds LAI creation and OnrampSession creation backend interactions
  stripe-crypto-onramp-example/build.gradle
  stripe-crypto-onramp-example/dependencies/dependencies.txt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/OnrampActivity.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/OnrampViewModel.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/network/CheckoutRequest.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/network/CreateAuthIntentRequest.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/network/CreateAuthIntentResponse.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/network/CreateOnrampSessionRequest.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/network/OnrampSessionResponse.kt
  stripe-crypto-onramp-example/src/main/java/com/stripe/android/crypto/onramp/example/network/TestBackendRepository.kt
Labels: accept-risky-change
